### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ghost** [Darthkpo/bob#6]
Any chance you can dual license this under a license allowing closed source usage? We need to embed a simple build system in a commercial application, and this is a good candidate. But we need to do some additional work on a fork (highly proprietary changes, not relevant for upstream inclusion)

Unfortunately, GPL prevents us from using Bob. I understand if you want to stick with GPL, just figured asking wouldn't hurt.

**Comment by guilledk** [comment]
Honestly when choosing a license the only thing I wanted was getting improvements back, but in the past day many people have told me they rather have a more permisive license.

bob will be under the MIT license from now on.

**Comment by ghost** [comment]
Great news
